---
- name: Downloading fah-client for x64
  include_tasks: download_fah_x64.yml
  #when: ansible_architecture == "x86_64"

- name: Install fah-client for x64
  include_tasks: install_fah.yml

- name: Configure fah-client
  include_tasks: configure_fah.yml

- name: Start fah-client
  include_tasks: start_fah.yml
